function [Ri Res] = calcRes(A,phi)
    [M N] = size(phi);
    % Calculate the residual
    Ri = A.P-A.S .* [zeros(1,N); phi(1:M-1,:)] ...		
	- A.W .* [zeros(M,1), phi(:,1:N-1)] ...		
	- A.O.* phi ...								
	- A.E .* [phi(:,2:N), zeros(M,1)] ...		
	- A.N .* [phi(2:M,:); zeros(1,N)];										
    Res = norm(Ri);
end