#If .mexrc.sh has not been modified for your ANSI compiler, uncomment
# the following two lines if you use GCC. Modify for your own ANSI
# compiler if different:
#MCC = CC=gcc
#MCFLAGS = CFLAGS=-ansi

mpgread:
	cmex $(MCC) $(MCFLAGS) mpgread.c util.c video.c parseblk.c \
		mvector.c decoders.c gdith.c jrevdct.c ordered2.c
